// Pulling source out of a model response, and stamping where it came from.

// Models wrap code in fences and often add prose around it. Take the first
// fenced block; a response with no block at all is a failure the UI shows
// verbatim rather than guessing at (spec section 6) -- silently treating
// prose as source would put "I am unable to help" into the editor.
export function extractSource(text) {
  // The opening run is 3-OR-MORE backticks (`{3,}`, greedy -- it grabs the
  // longest run present, e.g. all 4 of a four-backtick fence) and \1
  // requires the SAME LENGTH run to close it. A fixed ``` /```...```/``
  // pattern would treat a four-backtick fence's opening as only the first
  // three backticks, leaving the fourth as a leading stray character that
  // survives the info-string test below (it isn't a bare word) and becomes
  // line 1 of the "extracted" source -- a confusing `unexpected character`
  // compile error for source that was actually well-formed.
  const m = /(`{3,})([\s\S]*?)\1/.exec(String(text || ''))
  if (!m) return null
  let body = m[2]
  const nl = body.indexOf('\n')
  if (nl !== -1) {
    // The info string on a fenced code block is a bare word (```plantscript)
    // with no spaces or punctuation. Only strip a first line that actually
    // looks like one -- a model that puts code on the fence's own line
    // (```wrapper "x" match service 0x1234) must keep that line, since for
    // a wrapper it is the header and the single most load-bearing line.
    const firstLine = body.slice(0, nl)
    // Judge the tag on its trimmed self (CRLF line endings leave a
    // trailing \r on firstLine; a model may also pad with trailing
    // spaces) but slice off the whole line, \r and all, once it passes.
    const tagCandidate = firstLine.replace(/[ \t\r]+$/, '')
    if (/^[A-Za-z0-9_+-]*$/.test(tagCandidate)) body = body.slice(nl + 1)
  }
  body = body.replace(/\s+$/, '')
  return body.length > 0 ? body : null
}

// One line, prepended to generated source. Costs a comment and means an
// installed wrapper can be traced to the template and model that wrote it.
export function provenance(templateName, version, model) {
  return `# generated by planthub ai — ${templateName} v${version}, ${model}`
}
