// Pulling source out of a model response, and stamping where it came from.

// Models wrap code in fences and often add prose around it. Take the first
// fenced block; a response with no block at all is a failure the UI shows
// verbatim rather than guessing at (spec section 6) -- silently treating
// prose as source would put "I am unable to help" into the editor.
export function extractSource(text) {
  const m = /```[^\n]*\n([\s\S]*?)```/.exec(String(text || ''))
  if (!m) return null
  const body = m[1].replace(/\s+$/, '')
  return body.length > 0 ? body : null
}

// One line, prepended to generated source. Costs a comment and means an
// installed wrapper can be traced to the template and model that wrote it.
export function provenance(templateName, version, model) {
  return `# generated by planthub ai — ${templateName} v${version}, ${model}`
}
